language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler:2.0.1
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: vXJYtg0j5+sS7MCO/DfnDrJJoyTEjBmBQyaSDgI7GLlfhT3Da8r6oKvEctr15+QZOUEiK4rd01vAS69WdwBzF5ejm7OsSfHGDDxgs6cF/o+owhqZJRoN5Nll6Zf3tGEg6PrYAfJR91cCBTz3doaq4BwUhUrzxIQi8olR7tJJRf0DfmeJpjsf2zG5Ot9saaY6pSilgoKFOCPv3r3B6V4Wtu+MabctB8g0w3wseaK7ufPDWzdEwh9bSzbXriigr9hz3lZiXcqe4UYSy+cFJ140Jj9ABlXaS+ouRL/C+CET63LBKFEIdEn7a+kFSBbJhOfIpTj4bW36ijgXYdLXBnoCjOGQwQzBF+yY/HQ+sE6QIf6LCgJpxhDoWVESz/JAqcxyTB8w9TbLPYVM8nuE8hDV8gpkP3dorJA/sQHnkNjkF0iRAaepOddxOf9zhRuHcLKK3lyCf3dNB3ItCm2NUvPxISLfQsaFlmlGq0ZevPX6jUAy2Vq+MG3GsbbpNrjlpuv8gARqSuWZlcl+32herJtsue2bw5BOx1JMDiC+rMcs7AXaMJqlwZiQ2SXhsQBIBofsu0mMFY1W7JdSPwIbDSoFjEyOL0iCyq918HsZar7Q1WzE2zgLrOjv+3cVWT5pyeJQR1QWyi19qIN5x+1/CXiWNyiaVmQ8cNBgsLK5Z2AuzpU=
  app: vol4-capybara
  on:
    repo: netguru-code-college/vol4-capybara
env:
  secure: dWD0f30vrViyKASrtb4T79fIUcivRhOg9rnmdoDRZ1QPzWqqYfSx0YG6RNmtOYMMO+wpp3gPIV2o56GAdrG1bpnqG2x4PHtyfVzoRBsHQsgTeX4enYlRdo+qRV7jlSEQhmaOvWG4r3iezgSstOZ/zLYpIUV3H/BICIak0p3IJEJ1/GEmwNVnXlADHUmAndt5mjggbvbPKy76Jj6RyKJlh53gJe4yJ1LAr9gCmD7gLIT1YG1FtO4lvaklffPCRc8pBTqstN1ITRYnjwtSFx1rtgIVhYKenWhFbQEpHJPK66HB/yjVkum2f7JecBomHOPEJtt1qT2answ4xqzYZk7zfSMu1UGYVJwnSXDP9gqQehL/J2ItyQGiDKNze2Be9TH/aoUKLD8J5pEgtUmdLngwrjOD0z+/Zok6c5zxOWQJ4zdTsEAX7cjkgYeHKZUmvVgUMb2GrVV1AQyGFXSlZ0fvNQVu81pNAffRxTO5Zuuouxu/u+zqKkgtT/q8hdTkBh0VPx4xwHebcpUmTJnF53oIcoby5eOpJ2t2Vl5x9ElRkPRtRZcrT5LP6eZ+XJ0DeB53GLAqAGhMi+jnMF55h2i02c1jJIw4frfccHVGDb3gQpUvyhTHGB+m21B37XJKZbNkDpLiAacySLN+fVTLX9mLlAt5H1qZbhlSzo0q6xpvbPw=
