language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: MSFdv+Wo3X2R6tBOUEdDtIfuRQ+wRKR7pnGrzB5BvNaP8M6ex6Og7NRZbYsI9mdaMQctFEjwQP1MBe1sXULY+1BMVVbK6jm+yxxaOAFrj+gRIl++XazFHR5u/V9/i3et7dHn/jR97v1zQbdmJkHhvq95YqvD60rb9j5UCPmz6b5N4oJF6Io+WHttY9pE9Ffnm1hZTZwa1H7mMt2Vob3m0ijlaUVdVHv/q7PVw3hBKaJeTNEcyo+OpkaX4YjII8diUmZao/jvfDycNXF+xZQ0bhFzQErd/V4koci/1BLM3EasDDdi1hm3Y1FZr4zScXv/g0WbO3cHZy+dRnWTlqbGy7h0P0xEhQF5YgH3NgVUcKqzyFPuDWt0JIUXspQ0NZclNY5oGjowZ8LfE3RZ3X7uOblm9oUeu8sCB0R8/jCaAc/mDnaXL33tRIQ6fAROA7TcME8ulPYoHOyVs6XbNoh0VwbsafF+bXrEtMT4VPRmUyT+6QTh4DRk4GuVKxXvHL13lKZs+l0SW6AfXioEanGceay3qlLcARJ8EXjUcnMTd1AOPSqRXlU+V4GuRSjTrzcScZZSwm0ZJwgsipeVEG1x/Weg2de7V4OByr9/sPCBg/qTMr36yjcvbNrudILttYpPUr1nkV5Iu+Tu147KvJ4E7igegoBaFi/QatVQPmPISR0=
  app: vol4-capybara
  on:
    repo: netguru-code-college/vol4-capybara
env:
  secure: ILk2/m7ZdisyOVVKLH0zC7iQxJSo0hQLlpAD3yhSguM1fCEc9geV7HYdg7dYb96Q79T3Lx2WYSpxUV/GJApwvVS+we4UMMp2IgObF6pNlM2znHTiIzIfzOarDgTEjJR9t7Bqxk0BCOzR1o7iG4WGvhxMixUfnkpVSQNfBOkqzE1Xo7qQn0jqSBk8nPDElvWQvZbYp/egZzzTSyljVMFV4KBGIhbZZazGAF2Mc6ImzYSncHxVnGmdYrzW31D/Uig7f0zZnSavMSkmVYab9P0d6CsSepOckVeef4lczHIrqKY69XKnrOsv/4HDixD9hqBI8FkWGZrTYK4c6GiywOXFnku0PRgFk5wph/WGyU2hxgZik+gaWHr1Lw/jUVhfKeEOtQ/aAIPbIoOjd7Zy8iLGrWVYRdcW2pl+c1A0qPifEYefXxcXkAr6Egyp+AdfL/W3nOM0U792dnW/4GuWYvMdsr0urI9jBmJIO2nMy1kIUdZbXTs9XE3yW8RotVvx27smHvjsWycejlWfG21UG1Y1XccNftEJl4nXdzrrYXav+LLzTIr+0RjTPuF+zlMHdHZ3OHAo1/65CB+lDuwp6WzrDw04yy3JwvYgGv3mx1M2Wgfj7GrvYipkbjiTLZDDTtnFWwPAC9YMhxb/3Y0d1j2fxgffKDWbQ5rlBfwTH8ZewOU=
