language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler:2.0.1
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  skip_cleanup: true
  on: fixing_travis_day_2
  api_key:
    secure: W6zH02TQvrwuUXAcEdIDjk4UVFbuPCqdyBQ8cz65J+qL1UHggMJ2WFbv4xNgNJtAZPsDhNjKBQheY77na/hD4F06PkOjrmezyvpCLtPGDDlyNU8fEluBDrIUm36L59xzetUewNcOOoRaE+0AfBPpqaixx2VPHnyjPoruQ1xQOsHF5JEse3UAKU/dz6vEPDtky3V3GbV9RkfEkfXpPt4dIxe/o38qNYuEE54xdw6VofM/dPQxrwd6bElxTKdQMuiZ+hrVp6o+Vmqe1UzHbtWlNyLqTUny+eyQmliS5z7JvODgIeqHxvpLgwYJgqfYuvdq0fB865pOz9I8Yyhb55zrqGp++HTZGPreq+SMMdJ+b7l3k9kLO8Rhv3+j3an2Gx4MDdjV3fHqeVRA902/CX5Dx//uQLkbMY9oLVcObd23BjG+Uafk5Pxu479p8LklIX/3VVbxBI5TDS7Iiz1llB13AR5865eZ6K+iWGqrGtyngI+HMRvtThhmUCd4BdCgSgkeQOK0OGeObgiZHuyrVC119tQIR0tgPh+GuqHLz7sxO/CCuRrkhtksUi6duBnBdKByY4HW19QllxGsiJm3tt0ZRxkvkulS8FPdNQXQT7EO1+8iZOppfQKGN18fXKzGnCGeOAtuhE1vlr0JHcNlytt/Nz6zliC1tEcw42Pjpf5iO9I=
env:
  secure: dWD0f30vrViyKASrtb4T79fIUcivRhOg9rnmdoDRZ1QPzWqqYfSx0YG6RNmtOYMMO+wpp3gPIV2o56GAdrG1bpnqG2x4PHtyfVzoRBsHQsgTeX4enYlRdo+qRV7jlSEQhmaOvWG4r3iezgSstOZ/zLYpIUV3H/BICIak0p3IJEJ1/GEmwNVnXlADHUmAndt5mjggbvbPKy76Jj6RyKJlh53gJe4yJ1LAr9gCmD7gLIT1YG1FtO4lvaklffPCRc8pBTqstN1ITRYnjwtSFx1rtgIVhYKenWhFbQEpHJPK66HB/yjVkum2f7JecBomHOPEJtt1qT2answ4xqzYZk7zfSMu1UGYVJwnSXDP9gqQehL/J2ItyQGiDKNze2Be9TH/aoUKLD8J5pEgtUmdLngwrjOD0z+/Zok6c5zxOWQJ4zdTsEAX7cjkgYeHKZUmvVgUMb2GrVV1AQyGFXSlZ0fvNQVu81pNAffRxTO5Zuuouxu/u+zqKkgtT/q8hdTkBh0VPx4xwHebcpUmTJnF53oIcoby5eOpJ2t2Vl5x9ElRkPRtRZcrT5LP6eZ+XJ0DeB53GLAqAGhMi+jnMF55h2i02c1jJIw4frfccHVGDb3gQpUvyhTHGB+m21B37XJKZbNkDpLiAacySLN+fVTLX9mLlAt5H1qZbhlSzo0q6xpvbPw=
