language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler:2.0.1
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: abV9lV3534CQtAp1og/DgfQSY5ziyi/c4JR8GSfuOB+EztGJMv4lj6yBnCyYSwAH+bs4GIca+FsP4DVdK0CjClBUnsfeeWmHf5kobRzsLo9Xph5wM/zpUbou7Zx/kF8iB8gHR1nnDzaI5mmQeAcc2lb5PX4sACoS7ZGLBPlO0398TBYTPmfBolz4M/RQkH5RQvFqWhHwYGUbiSZvudA1KlFCQXBToUQKzvzh0RPWVhmUW/h9FBkEhcQGMf9yfNeajIncSCrlrCY2+FyX8gjjROZM+TAm5G0K4PUAhpu5dFmqszrNrLwFE8uSyr/913WBBLdd/vCGSsx5oKK3yOqOok4DpCuiIMHpTZCydIdwvkMK3cXcxuibRkPF4pO/Kzl1PrNINt5dGrA3cWvH1YphdWKQdTg93nXaLOY2fr1EFBD3uOu1tbCQxGIcQlGn9RYimkKzTflJbeO2Fx2BaREje3u3m5VXztI+PckMHlWaMSxKwBLiAra5zNjBtO0H+pf3ZJJDyc3J8X9KdfS6RUUyNWw5xbsHBeRuE3+fes++xQr8Vk+CN8eChLuqvZ9P7C2qyOZ5UGHPkBBHuX+v5Z2c++d8uHF4VWnTwcyCBLKf/VrhqGXaC57NDl2yd2rfPmpKAUrpTxDCND3rQxCJ7B9WmWMkefoY9/n8uCnV6RZSKzw=
env:
  secure: dWD0f30vrViyKASrtb4T79fIUcivRhOg9rnmdoDRZ1QPzWqqYfSx0YG6RNmtOYMMO+wpp3gPIV2o56GAdrG1bpnqG2x4PHtyfVzoRBsHQsgTeX4enYlRdo+qRV7jlSEQhmaOvWG4r3iezgSstOZ/zLYpIUV3H/BICIak0p3IJEJ1/GEmwNVnXlADHUmAndt5mjggbvbPKy76Jj6RyKJlh53gJe4yJ1LAr9gCmD7gLIT1YG1FtO4lvaklffPCRc8pBTqstN1ITRYnjwtSFx1rtgIVhYKenWhFbQEpHJPK66HB/yjVkum2f7JecBomHOPEJtt1qT2answ4xqzYZk7zfSMu1UGYVJwnSXDP9gqQehL/J2ItyQGiDKNze2Be9TH/aoUKLD8J5pEgtUmdLngwrjOD0z+/Zok6c5zxOWQJ4zdTsEAX7cjkgYeHKZUmvVgUMb2GrVV1AQyGFXSlZ0fvNQVu81pNAffRxTO5Zuuouxu/u+zqKkgtT/q8hdTkBh0VPx4xwHebcpUmTJnF53oIcoby5eOpJ2t2Vl5x9ElRkPRtRZcrT5LP6eZ+XJ0DeB53GLAqAGhMi+jnMF55h2i02c1jJIw4frfccHVGDb3gQpUvyhTHGB+m21B37XJKZbNkDpLiAacySLN+fVTLX9mLlAt5H1qZbhlSzo0q6xpvbPw=
