language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: JhIust4D74Azzfau/8NZJF4xzXH+wDTu6hEZy6ZLhO6zHiI3+hkFIIasVRwjF4w7qwHrCQqs5ka4INqb2wmkI0Qxx9FaLYqLz92IlGAqnvNc4KIuCc2ePXUSyQ88lar4feBp86b98nvttiOIZc0wHKF2giVMZ5lkhWHLbT6ozId48/k/7l9JByQezxTBLThjrZ/mo/QEDIcSLmdYv092+xIF1dJEu09O3oKloDLpuoOIAMAXDLeQnwsPj76/ei4VdMEcWgdBM7CsnOOGhhOILh2cU8o7I/KFBx220a+l6YsFtuHb0xyPMWcKq/P6OXrtWmiyUzyaeFkORc6d4YWlGrgrPdAGe1a7DpiCskB80ogVSdObl8GFMCfmE+kky2Wi3VmTLQvF10J/iRcNhMDV57dunBMOFMg/Y3VnmSh4KSJ2Q1HKM3fYCY/tTQ+8dqbwuEinAPslQWiGW4HvW9sv1cE/MwgqhVzqB4WHC6UBlMTZM9M4amjsTFa4/YQtYg3Hb0BPIolWGLpaKlLD7KIDBFgDLs4FQoilgFLhGQCWCMxIicURLoqw9iAfODftUyLWk/IcCqgppuC2bc2nfhyRA5bZGTe2yFj6uwUcaMApnYy37X4DsXBwbWp1BqYfzLJ27xERF/oZZ1FBmCjXjSSIkrE2q6ch+8TTzNWW+bJ8hJE=
env:
  secure: ILk2/m7ZdisyOVVKLH0zC7iQxJSo0hQLlpAD3yhSguM1fCEc9geV7HYdg7dYb96Q79T3Lx2WYSpxUV/GJApwvVS+we4UMMp2IgObF6pNlM2znHTiIzIfzOarDgTEjJR9t7Bqxk0BCOzR1o7iG4WGvhxMixUfnkpVSQNfBOkqzE1Xo7qQn0jqSBk8nPDElvWQvZbYp/egZzzTSyljVMFV4KBGIhbZZazGAF2Mc6ImzYSncHxVnGmdYrzW31D/Uig7f0zZnSavMSkmVYab9P0d6CsSepOckVeef4lczHIrqKY69XKnrOsv/4HDixD9hqBI8FkWGZrTYK4c6GiywOXFnku0PRgFk5wph/WGyU2hxgZik+gaWHr1Lw/jUVhfKeEOtQ/aAIPbIoOjd7Zy8iLGrWVYRdcW2pl+c1A0qPifEYefXxcXkAr6Egyp+AdfL/W3nOM0U792dnW/4GuWYvMdsr0urI9jBmJIO2nMy1kIUdZbXTs9XE3yW8RotVvx27smHvjsWycejlWfG21UG1Y1XccNftEJl4nXdzrrYXav+LLzTIr+0RjTPuF+zlMHdHZ3OHAo1/65CB+lDuwp6WzrDw04yy3JwvYgGv3mx1M2Wgfj7GrvYipkbjiTLZDDTtnFWwPAC9YMhxb/3Y0d1j2fxgffKDWbQ5rlBfwTH8ZewOU=
